# Generated by Django 2.0 on 2017-12-07 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_lat', models.DecimalField(decimal_places=7, max_digits=11)),
                ('location_lon', models.DecimalField(decimal_places=7, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=50)),
                ('node_states', models.CharField(choices=[(0, 'VERDE'), (1, 'AMARILLO'), (2, 'ROJO')], max_length=1)),
                ('node_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapView.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Node_status_records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapView.Node')),
            ],
        ),
    ]
