# Generated by Django 2.0 on 2017-12-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapView', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='node_name',
            new_name='node_ip',
        ),
    ]
