# Generated by Django 2.0 on 2017-12-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapView', '0002_auto_20171216_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node_status_records',
            name='node',
        ),
        migrations.RemoveField(
            model_name='node',
            name='node_states',
        ),
        migrations.DeleteModel(
            name='Node_status_records',
        ),
    ]
