# Generated by Django 2.0 on 2017-12-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapView', '0003_auto_20171218_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_states',
            field=models.CharField(choices=[(0, 'VERDE'), (1, 'AMARILLO'), (2, 'ROJO')], default=2, max_length=1),
        ),
    ]
