# Generated by Django 2.0 on 2018-01-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapView', '0004_node_node_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_hardware',
            field=models.CharField(choices=[(0, 'Ubiquity Unify AP Outdoor +'), (1, 'Raspberry Pi 3 Model B')], default=0, max_length=1),
        ),
    ]
