# Generated by Django 2.0 on 2018-01-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapView', '0005_node_node_hardware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_hardware',
            field=models.CharField(choices=[(0, 'UBIQUITY'), (1, 'RASPBERRY')], default=0, max_length=1),
        ),
    ]
