# Generated by Django 2.0 on 2018-01-25 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapView', '0006_auto_20180122_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node_log_records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('record_electric_current', models.DecimalField(decimal_places=3, max_digits=5)),
                ('record_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='node',
            name='node_hardware',
            field=models.CharField(choices=[(0, 'UBIQUITY'), (1, 'RASPBERRY')], default='UBIQUITY', max_length=1),
        ),
        migrations.AddField(
            model_name='node_log_records',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapView.Node'),
        ),
    ]
