# Generated by Django 2.0 on 2018-01-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapView', '0007_auto_20180125_1416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Node_log_records',
            new_name='NodeLogRecords',
        ),
    ]
