# Generated by Django 2.0 on 2018-01-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapView', '0008_auto_20180125_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='id',
        ),
        migrations.AlterField(
            model_name='node',
            name='node_ip',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
