# Generated by Django 2.0 on 2018-01-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapView', '0009_auto_20180125_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodelogrecords',
            old_name='node',
            new_name='record_node',
        ),
    ]
